{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.rikka.shizuku",
    "module": "aidl",
    "version": "13.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aidl-13.1.5.aar",
          "url": "aidl-13.1.5.aar",
          "size": 23673,
          "sha512": "0090e17cf54dcdb3a718668cb98499e67a8de477826a199b544e219e0356a0e1bd86011dfbb3d761e17741a8bd7bae7927465006200164d2315a9c1e2cbbac13",
          "sha256": "33fe7191cdd69fcb66d649264f3b0c47acb2f3d6343afc05b98dbbff6f221963",
          "sha1": "457504c277d796adea698b80b4e765f98dd0799a",
          "md5": "5f37ed1acb2605eaeed010955fb5d8f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-13.1.5.aar",
          "url": "aidl-13.1.5.aar",
          "size": 23673,
          "sha512": "0090e17cf54dcdb3a718668cb98499e67a8de477826a199b544e219e0356a0e1bd86011dfbb3d761e17741a8bd7bae7927465006200164d2315a9c1e2cbbac13",
          "sha256": "33fe7191cdd69fcb66d649264f3b0c47acb2f3d6343afc05b98dbbff6f221963",
          "sha1": "457504c277d796adea698b80b4e765f98dd0799a",
          "md5": "5f37ed1acb2605eaeed010955fb5d8f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-13.1.5-sources.jar",
          "url": "aidl-13.1.5-sources.jar",
          "size": 9104,
          "sha512": "32f163afe0d614104d733b6db7360cd16a9b21d7c2039431d9f0a1515c5842b03cda443a054fc35b3bda382aa9a83e23afe9d247b26ce6ab4fcb14c975d8df95",
          "sha256": "2c5207da142aa9aa464d1630559f1c7ddbc896fdb84a22efa8d09fa0d47f18a2",
          "sha1": "bd898ad4ced48a553565a7fe5738ffb3a12b8c2a",
          "md5": "6e0c334d7346433f2b1baad35cf0067a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aidl-13.1.5-javadoc.jar",
          "url": "aidl-13.1.5-javadoc.jar",
          "size": 337481,
          "sha512": "7e40c30867808369b6f06d0e77cfca1580a4eb67990d189e626cf2a1f18ee6206c2494fd0df043f01fd4f4174688ded7bc5390a3f867ed59d48de6580db72bea",
          "sha256": "74e284811ca875ef6d27cab7af4a88da9f2bd22b4b33986f3ef9e6b4cf349264",
          "sha1": "dd680cca8b00c5ae5db78a3cb2b239d9e571cc72",
          "md5": "0ebe96a19b80f05c7b5739e2c6ae708b"
        }
      ]
    }
  ]
}
