{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.rikka.shizuku",
    "module": "shared",
    "version": "13.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "shared-13.1.5.aar",
          "url": "shared-13.1.5.aar",
          "size": 2614,
          "sha512": "8460f161a50fce4f2517bdf0165ed856d73bb256b2083cf7321be9c4633dbab9b095597fafee6f79cc5adde6c1f043b7e1a7f85a69f9d780865e056f09eea21c",
          "sha256": "4659642c9339be0a26e9c65bb8648f7ad6d8f4a465f557993ccbc78802381635",
          "sha1": "8c4e73ce466cd27aff10565d2ec49809c258f974",
          "md5": "83ae87bf353ae0ec216d59cdaf466838"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.rikka.shizuku",
          "module": "aidl",
          "version": {
            "requires": "13.1.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-13.1.5.aar",
          "url": "shared-13.1.5.aar",
          "size": 2614,
          "sha512": "8460f161a50fce4f2517bdf0165ed856d73bb256b2083cf7321be9c4633dbab9b095597fafee6f79cc5adde6c1f043b7e1a7f85a69f9d780865e056f09eea21c",
          "sha256": "4659642c9339be0a26e9c65bb8648f7ad6d8f4a465f557993ccbc78802381635",
          "sha1": "8c4e73ce466cd27aff10565d2ec49809c258f974",
          "md5": "83ae87bf353ae0ec216d59cdaf466838"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-13.1.5-sources.jar",
          "url": "shared-13.1.5-sources.jar",
          "size": 1806,
          "sha512": "90728c0749c023c51c851ac9d93606a330f0a7b124f659530d4f3b657b19ab1ed674d20b979e6d900a7e2eaf8fd30422546c752637fbd0c9a07655608d4a5f05",
          "sha256": "5b062211624678129fd332fc2e5a1cb228f441b49c3c5aef96b72f2352c7f9f9",
          "sha1": "e8314297bb27497539219241e59d8c03cb866427",
          "md5": "5f2a76a84e5ff130ff42c5d4814e2f79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-13.1.5-javadoc.jar",
          "url": "shared-13.1.5-javadoc.jar",
          "size": 266007,
          "sha512": "c2040f498b0b4650577424121de763b1fe53f89654541286952e879b34cd87429bc01da4029e2616d0d4843370f82dd2f93b6daafa6c1612b1caca0353d97654",
          "sha256": "dbc5960305fed08cbbbbc64e68c3137165b58a9f3f04dd013078a59617bfebb2",
          "sha1": "dae91027ab9d2050cc8c9b617b732c9eac0e0434",
          "md5": "747dc9bc468b8e6eba7b5847e98e6905"
        }
      ]
    }
  ]
}
